name: Merciful
favicon: null
layout_spectrum: 0.14353380841203034
typography_spectrum: 0.8685077517293394
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.09008412389084697
  lightness: 0.24849320435896516
  saturation: 0.28830516268499196
  rhythmicContrast: 0.10943609266541898
purpose: []
