name: Merciful
favicon: null
layout_spectrum: 0.39768
typography_spectrum: 0.84789
title: Essential Life
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000002'
    - '#5a3966'
    - '#3c1541'
    - '#815d8d'
    - '#ad8eb5'
  brandStrength: 0.5
  lightness: 0.9375
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
